// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaMaquila.Server;

#nullable disable

namespace SistemaMaquila.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.EmpleadoFolder.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostoMinutoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LineaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LineaId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.HabilidadEmpleadoFolder.HabilidadEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EficienciaSocio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("OperacionId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("OperacionId");

                    b.ToTable("HabilidadesEmpleados");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.InventarioLineaFolder.InventarioLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("LineaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMaquinaId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LineaId");

                    b.HasIndex("TipoMaquinaId");

                    b.ToTable("InventarioLineas");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.LineaFolder.Linea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EficienciaHistorica")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Lineas");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.OperacionFolder.Operacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SAMEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoMaquinaId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TipoMaquinaId");

                    b.ToTable("Operaciones");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.OperacionPrendaFolder.OperacionPrenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OperacionId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenSecuencia")
                        .HasColumnType("int");

                    b.Property<int>("PrendaId")
                        .HasColumnType("int");

                    b.Property<decimal>("SAMReal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OperacionId");

                    b.HasIndex("PrendaId");

                    b.ToTable("OperacionPrendas");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.PrendaFolder.Prenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiempoCambioLineaMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Prendas");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.ProgramacionDiariaFolder.ProgramacionDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadObjetivo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineaId")
                        .HasColumnType("int");

                    b.Property<int>("PrendaId")
                        .HasColumnType("int");

                    b.Property<int>("SecuenciaDia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineaId");

                    b.HasIndex("PrendaId");

                    b.ToTable("ProgracionDiaria");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.TipoMaquinaFolder.TipoMaquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TipoMaquinas");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.EmpleadoFolder.Empleado", b =>
                {
                    b.HasOne("SistemaMaquila.Shared.Entidades.LineaFolder.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linea");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.HabilidadEmpleadoFolder.HabilidadEmpleado", b =>
                {
                    b.HasOne("SistemaMaquila.Shared.Entidades.EmpleadoFolder.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMaquila.Shared.Entidades.OperacionFolder.Operacion", "Operacion")
                        .WithMany()
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.InventarioLineaFolder.InventarioLinea", b =>
                {
                    b.HasOne("SistemaMaquila.Shared.Entidades.LineaFolder.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMaquila.Shared.Entidades.TipoMaquinaFolder.TipoMaquina", "TipoMaquina")
                        .WithMany()
                        .HasForeignKey("TipoMaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linea");

                    b.Navigation("TipoMaquina");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.OperacionFolder.Operacion", b =>
                {
                    b.HasOne("SistemaMaquila.Shared.Entidades.TipoMaquinaFolder.TipoMaquina", "TipoMaquina")
                        .WithMany()
                        .HasForeignKey("TipoMaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMaquina");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.OperacionPrendaFolder.OperacionPrenda", b =>
                {
                    b.HasOne("SistemaMaquila.Shared.Entidades.OperacionFolder.Operacion", "Operacion")
                        .WithMany()
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMaquila.Shared.Entidades.PrendaFolder.Prenda", "Prenda")
                        .WithMany()
                        .HasForeignKey("PrendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operacion");

                    b.Navigation("Prenda");
                });

            modelBuilder.Entity("SistemaMaquila.Shared.Entidades.ProgramacionDiariaFolder.ProgramacionDiaria", b =>
                {
                    b.HasOne("SistemaMaquila.Shared.Entidades.LineaFolder.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMaquila.Shared.Entidades.PrendaFolder.Prenda", "Prenda")
                        .WithMany()
                        .HasForeignKey("PrendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linea");

                    b.Navigation("Prenda");
                });
#pragma warning restore 612, 618
        }
    }
}
